export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAER_ERRORS';
export const SET_ALERT ="SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const CUSTOMER_SEARCH_LOADED ="CUSTOMER_SEARCH_LOADED"
export const ERR_NO_CUSTOMER_FOUND ="ERR_NO_CUSTOMER_FOUND";
export const SET_LOADING ="SET_LOADING";
export const STOCK_SEARCH = "STOCK_SEARCH";


